# ItemTrackers by 89apt89

# Outputs useful debug information to console. Only enable this if you know what you're doing (or apt asked you to :p)
debug-mode: false

# Should users require the `itemtrackers.apply.[tracker_name]` permission to apply a tracker?
permission-based-application: false

# Should ItemTrackers stop you from using application items in crafting recipes?
disable-application-item-craft: true

# Should ItemTrackers stop you from renaming the application items in an anvil?
disable-application-item-rename: true