name: ItemTrackers
version: ${project.version}
main: systems.kscott.itemtrackers.ItemTrackers
api-version: 1.14
description: StatTrak-esque items in Minecraft!
commands:
  it:
    description: Main plugin command
    permission: itemtrackers.main

permissions:
  itemtrackers.main:
    default: op
    description: Main plugin command